# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ttt_service_pb2 as ttt__service__pb2


class TTTStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinMatchmaking = channel.unary_stream(
                '/protos.TTT/JoinMatchmaking',
                request_serializer=ttt__service__pb2.User.SerializeToString,
                response_deserializer=ttt__service__pb2.Response.FromString,
                )


class TTTServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinMatchmaking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTTServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinMatchmaking': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinMatchmaking,
                    request_deserializer=ttt__service__pb2.User.FromString,
                    response_serializer=ttt__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.TTT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TTT(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinMatchmaking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protos.TTT/JoinMatchmaking',
            ttt__service__pb2.User.SerializeToString,
            ttt__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
